###
### You can perform these requests with vscode's "Rest Client" extension
###

### Register a booking
POST http://localhost:3000/bookings/ HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjYyMjUwNWExNTQ4MjVmY2M2YjE2ZjkiLCJlbWFpbCI6ImJvb2tlckBib29rZXIuY29tIiwiaWF0IjoxNjAwMzU4NTc5LCJleHAiOjE2MDAzNjIxNzl9.d7IJY_U1Zmfjw75Ae9QYzIcilir6rHpuV1TfhLdPwHA


{
  "advertId": "5f636fba9b86674618714177",
  "startDate": "2020-10-20",
  "endDate": "2020-10-27"
}

### Get all bookings
GET http://localhost:3000/bookings/ HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjYyMjUwNWExNTQ4MjVmY2M2YjE2ZjkiLCJlbWFpbCI6ImJvb2tlckBib29rZXIuY29tIiwiaWF0IjoxNjAwMzYxNjAxLCJleHAiOjE2MDAzNjUyMDF9.x-dKyWcbfjoBY8GPfv1xWgtVgB-uXT_EplJ_1X0vRiw

### Get specific booking with its Id
GET http://localhost:3000/bookings/5f636fd19b86674618714179 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjYyMjUwNWExNTQ4MjVmY2M2YjE2ZjkiLCJlbWFpbCI6ImJvb2tlckBib29rZXIuY29tIiwiaWF0IjoxNjAwMzU4NTc5LCJleHAiOjE2MDAzNjIxNzl9.d7IJY_U1Zmfjw75Ae9QYzIcilir6rHpuV1TfhLdPwHA

### Update a specific booking
PUT http://localhost:3000/bookings/5f636fd19b86674618714179 HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjYyMjUwNWExNTQ4MjVmY2M2YjE2ZjkiLCJlbWFpbCI6ImJvb2tlckBib29rZXIuY29tIiwiaWF0IjoxNjAwMzYxNjAxLCJleHAiOjE2MDAzNjUyMDF9.x-dKyWcbfjoBY8GPfv1xWgtVgB-uXT_EplJ_1X0vRiw


{
  "startDate": "2020-10-23",
  "endDate": "2020-12-25"
}

### Delete specific booking 
DELETE http://localhost:3000/bookings/5f636fd19b86674618714179 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjYyMjUwNWExNTQ4MjVmY2M2YjE2ZjkiLCJlbWFpbCI6ImJvb2tlckBib29rZXIuY29tIiwiaWF0IjoxNjAwMzYxNjAxLCJleHAiOjE2MDAzNjUyMDF9.x-dKyWcbfjoBY8GPfv1xWgtVgB-uXT_EplJ_1X0vRiw