### Register an advert
POST http://localhost:3000/adverts/ HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjVmNDI5N2NiNGVlNTZhYWU0NGRmMGQiLCJlbWFpbCI6ImpvaGFuM0BnbWFpbC5jb20iLCJpYXQiOjE2MDAyNzUyMzEsImV4cCI6MTYwMDI3ODgzMX0.hi9XxilMqayK91gUc4tlUR8ULmVBCj0ZItO8uqWAPzw


{
  "cabinId": "5f6249ce07f1e782d2e1968d",
  "pricePerDay": 24921,
  "startDate": "2020-09-30",
  "endDate": "2020-10-16"
}

### Get all adverts
GET http://localhost:3000/adverts/ HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjVmNDI5N2NiNGVlNTZhYWU0NGRmMGQiLCJlbWFpbCI6ImpvaGFuM0BnbWFpbC5jb20iLCJpYXQiOjE2MDAyNzUyMzEsImV4cCI6MTYwMDI3ODgzMX0.hi9XxilMqayK91gUc4tlUR8ULmVBCj0ZItO8uqWAPzw

### Get specific advert with its Id
GET http://localhost:3000/adverts/5f6219a12a746a4ed8d8d1bf HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjYyMjUwNWExNTQ4MjVmY2M2YjE2ZjkiLCJlbWFpbCI6ImJvb2tlckBib29rZXIuY29tIiwiaWF0IjoxNjAwMjY3NTk0LCJleHAiOjE2MDAyNzExOTR9.g6HLz6JgxR63VnJag_l2bdlFr0STxlFR2_AE-YeQ9_Y

### Update a specific advert
PUT http://localhost:3000/adverts/5f6219a12a746a4ed8d8d1bf HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjVmNDI5N2NiNGVlNTZhYWU0NGRmMGQiLCJlbWFpbCI6ImpvaGFuM0BnbWFpbC5jb20iLCJpYXQiOjE2MDAyNjgwMTksImV4cCI6MTYwMDI3MTYxOX0.0tcMqKUHLMkKnbAi0fEze9e2ukWDnoQDugtYbbkzAD0


{
  "pricePerDay": 69,
  "endDate": "2020-10-28",
  "startDate": "2020-10-22"
}

### Delete specific advert 
DELETE http://localhost:3000/adverts/5f6219a12a746a4ed8d8d1bf HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjVmNDI5N2NiNGVlNTZhYWU0NGRmMGQiLCJlbWFpbCI6ImpvaGFuM0BnbWFpbC5jb20iLCJpYXQiOjE2MDAyNjgwNzMsImV4cCI6MTYwMDI3MTY3M30.6q0eaArkssA7V1LByso2VqtWVgbiIP6yJcb4wWIco0w