### REGISTER
POST http://localhost:3000/cabins/ HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjYyMjUwNWExNTQ4MjVmY2M2YjE2ZjkiLCJlbWFpbCI6ImJvb2tlckBib29rZXIuY29tIiwiaWF0IjoxNjAwMzM3MTk4LCJleHAiOjE2MDAzNDA3OTh9.kRGlpVSZc81jQxNJig_zGO-c4D3YdzCNCQUmRbf4rO0



{
  "address": "bookerstr 555",
  "squarageCabin": 502,
  "squarageProperty": 321,
  "sauna": true,
  "beachfront": false
}

### Get all cabins
GET http://localhost:3000/cabins/ HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjYyMjUwNWExNTQ4MjVmY2M2YjE2ZjkiLCJlbWFpbCI6ImJvb2tlckBib29rZXIuY29tIiwiaWF0IjoxNjAwMzM3MTk4LCJleHAiOjE2MDAzNDA3OTh9.kRGlpVSZc81jQxNJig_zGO-c4D3YdzCNCQUmRbf4rO0
### Get specific cabin with its Id
GET http://localhost:3000/cabins/5f5f42efcb4ee56aae44df0f HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjVmNDI5N2NiNGVlNTZhYWU0NGRmMGQiLCJlbWFpbCI6ImpvaGFuM0BnbWFpbC5jb20iLCJpYXQiOjE2MDAyNjQzMzIsImV4cCI6MTYwMDI2NzkzMn0.lmtYaKxxp-E__XrehmW-5yj6u_JHQF4rmcPPISMZ0nE

### Update a specific cabin
PUT http://localhost:3000/cabins/5f621bc06f6b6855380c5062 HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjVmNDI5N2NiNGVlNTZhYWU0NGRmMGQiLCJlbWFpbCI6ImpvaGFuM0BnbWFpbC5jb20iLCJpYXQiOjE2MDAyNjQzMzIsImV4cCI6MTYwMDI2NzkzMn0.lmtYaKxxp-E__XrehmW-5yj6u_JHQF4rmcPPISMZ0nE


{
  "address": "waystreet 1234",
  "squarageProperty": 321,
  "sauna": true,
  "beachfront": false
}

### Delete specific cabin 
DELETE http://localhost:3000/cabins/5f5dec40be89542b312cdd0f HTTP/1.1
Authorization: Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjVmNDI5N2NiNGVlNTZhYWU0NGRmMGQiLCJlbWFpbCI6ImpvaGFuM0BnbWFpbC5jb20iLCJpYXQiOjE2MDAyNjQzMzIsImV4cCI6MTYwMDI2NzkzMn0.lmtYaKxxp-E__XrehmW-5yj6u_JHQF4rmcPPISMZ0nE
