POST http://localhost:63501/rooms HTTP/1.1
Content-Type: application/json

{
    "name": "yo dawg",
    "asdasd": "wrongvalue",
    "computers": 8
}

###
GET http://localhost:63501/rooms HTTP/1.1
Content-Type: application/json

{
    "name": "yo dawg",    
    "seats": 1337,
    "computers": 8
}

###
PUT http://localhost:63501/rooms/2 HTTP/1.1
Content-Type: application/json

{
    "name": "yo man",
    "seats": 300,
    "computers": 9
}