### REGISTER
POST http://localhost:3000/users/register HTTP/1.1
content-type: application/json


{
  "email": "booker@booker.com",
  "firstName": "Boooo",
  "lastName": "Ker",
  "password": "asdasdasd"
}

### LOGIN
POST http://localhost:3000/users/login HTTP/1.1
content-type: application/json


{
  "email": "johan3@gmail.com",
  "password": "asdasdasd"
}

### GET A USER
GET http://localhost:3000/users/5f5cdbe51c49d8340a8725dc HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjVkZmM4YjRlMWVmOTM5NGU1M2VmMWIiLCJlbWFpbCI6ImpvaGFuQGdtYWlsLmNvbSIsImlhdCI6MTYwMDAwMzM4NywiZXhwIjoxNjAwMDAzNjg3fQ._lDshIoa6fkL3agv94MOt-M9qWc4_nGeU0MVxpLqf-Q

### UPDATE A USER
PUT http://localhost:3000/users/5f5cf6f3f3199a5046647607 HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjVkZmM4YjRlMWVmOTM5NGU1M2VmMWIiLCJlbWFpbCI6ImpvaGFuQGdtYWlsLmNvbSIsImlhdCI6MTYwMDAwMzM4NywiZXhwIjoxNjAwMDAzNjg3fQ._lDshIoa6fkL3agv94MOt-M9qWc4_nGeU0MVxpLqf-Q


{
  "lastName": "sista namn"
}

### DELETE A USER

DELETE http://localhost:3000/users/5f5dfc8b4e1ef9394e53ef1b HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjVkZmM4YjRlMWVmOTM5NGU1M2VmMWIiLCJlbWFpbCI6ImpvaGFuQGdtYWlsLmNvbSIsImlhdCI6MTYwMDAwNjM3OSwiZXhwIjoxNjAwMDA2Njc5fQ.TJGYFnqSGRBEB3ZBJTD3V19lL6i8GFRqInNfjMSsh5o