POST http://localhost:3000/users/register HTTP/1.1
content-type: application/json


{
  "email": "user1@user.com",
  "firstName": "user",
  "lastName": "1",
  "password": "12345678"
}

###

POST http://localhost:3000/users/login HTTP/1.1
content-type: application/json


{
  "email": "user1@user.com",
  "firstName": "user",
  "lastName": "1",
  "password": "12345678"
}

### Testing JWT token mechanics:

GET http://localhost:3000/users HTTP/1.1
content-type: application/json
Authorization: eyJhbdGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjU3NzFhMTlhMTJiZjVmZmE2ZThlYmMiLCJlbWFpbCI6InVzZXIxQHVzZXIuY29tIiwiaWF0IjoxNTk5NTY3MzI0LCJleHAiOjE1OTk1Njc2MjR9.d5KL0zlDutNRo95Rh5O9Ajz1pOF7AdsPVqgNgZRHrPU
